# Generated by Django 3.1.3 on 2020-11-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201105_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.CharField(default='Python', max_length=100),
        ),
    ]
