# Generated by Django 3.1.3 on 2020-11-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201105_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='college_name',
            field=models.CharField(default='St. Peters', max_length=100),
        ),
    ]
